name: Reorder JSON Translations

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:     # Permet d'exécuter le workflow manuellement

jobs:
  reorder_json:
    # Exécute le job si la PR est fusionnée OU si le workflow est déclenché manuellement
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Reorder translations
        run: node ./.github/workflows/scripts/reorder-json.js

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "Aucun changement à appliquer."
            exit 0
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add translations/
          git commit -m "Réorganisation des traductions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}