name: Reorder JSON after PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  reorder_json:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'weblate-translations'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Reorder translations
        run: node ./.github/workflows/reorder.js

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add translations/
          git commit -m "Réorganisation des traductions après fusion de la PR"
          git push