name: Update Language Sources

on:
  schedule:
    - cron:  '0 0 * * *'  # Exécuter une fois par jour à minuit
  workflow_dispatch:  # Permet de déclencher manuellement
  push:
    paths:
      - 'projects.json'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Projects Source Json
        run: | 
          npm i -D axios
          node ./.github/workflows/update.js
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "french/* english/*"
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}