name: Update Language Sources

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit UTC
  workflow_dispatch:     # Permet d'exécuter le workflow manuellement
  push:
    paths:
      - 'projects.json'  # Déclenche sur modification du fichier projects.json

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Assure les permissions nécessaires pour push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour avoir l'historique complet

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i -D axios js-yaml

      - name: Update translations
        run: node ./.github/workflows/update.js

      - name: Commit changes if needed
        run: |
          if git diff --quiet; then
            echo "Aucun changement détecté"
            exit 0
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add translations/
          git commit -m "Mise à jour des sources de traduction [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}