name: Update Language Sources

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'projects.json'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour push

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i -D axios

      - name: Update translations
        run: node ./.github/workflows/scripts/update-sources.js

      - name: Show changes
        run: |
          git status
          git diff --stat

      - name: Commit & Push
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41910982+github-actions[bot]@users.noreply.github.com"
          git add translations/
          git diff --staged --quiet || git commit -m "Auto-update translations [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}